export const COUNTRIES = [
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Afrique du Sud', label: 'Afrique du Sud' },
  { value: 'Albanie', label: 'Albanie' },
  { value: 'Algérie', label: 'Algérie' },
  { value: 'Allemagne', label: 'Allemagne' },
  { value: 'Andorre', label: 'Andorre' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Antigua-et-Barbuda', label: 'Antigua-et-Barbuda' },
  { value: 'Arabie Saoudite', label: 'Arabie Saoudite' },
  { value: 'Argentine', label: 'Argentine' },
  { value: 'Arménie', label: 'Arménie' },
  { value: 'Australie', label: 'Australie' },
  { value: 'Autriche', label: 'Autriche' },
  { value: 'Azerbaïdjan', label: 'Azerbaïdjan' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bahreïn', label: 'Bahreïn' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Barbade', label: 'Barbade' },
  { value: 'Belgique', label: 'Belgique' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Bénin', label: 'Bénin' },
  { value: 'Bhoutan', label: 'Bhoutan' },
  { value: 'Biélorussie', label: 'Biélorussie' },
  { value: 'Birmanie', label: 'Birmanie' },
  { value: 'Bolivie', label: 'Bolivie' },
  { value: 'Bosnie-Herzégovine', label: 'Bosnie-Herzégovine' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Brésil', label: 'Brésil' },
  { value: 'Brunei', label: 'Brunei' },
  { value: 'Bulgarie', label: 'Bulgarie' },
  { value: 'Burkina Faso', label: 'Burkina Faso' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cambodge', label: 'Cambodge' },
  { value: 'Cameroun', label: 'Cameroun' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Cap-Vert', label: 'Cap-Vert' },
  { value: 'République centrafricaine', label: 'République centrafricaine' },
  { value: 'Chili', label: 'Chili' },
  { value: 'Chine', label: 'Chine' },
  { value: 'Chypre', label: 'Chypre' },
  { value: 'Colombie', label: 'Colombie' },
  { value: 'Comores', label: 'Comores' },
  { value: 'Congo', label: 'Congo' },
  { value: 'République démocratique du Congo', label: 'République démocratique du Congo' },
  { value: 'Corée du Sud', label: 'Corée du Sud' },
  { value: 'Corée du Nord', label: 'Corée du Nord' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: "Côte d'Ivoire", label: "Côte d'Ivoire" },
  { value: 'Croatie', label: 'Croatie' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Danemark', label: 'Danemark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominique', label: 'Dominique' },
  { value: 'Égypte', label: 'Égypte' },
  { value: 'Émirats arabes unis', label: 'Émirats arabes unis' },
  { value: 'Équateur', label: 'Équateur' },
  { value: 'Érythrée', label: 'Érythrée' },
  { value: 'Espagne', label: 'Espagne' },
  { value: 'Estonie', label: 'Estonie' },
  { value: 'États-Unis', label: 'États-Unis' },
  { value: 'Éthiopie', label: 'Éthiopie' },
  { value: 'Fidji', label: 'Fidji' },
  { value: 'Finlande', label: 'Finlande' },
  { value: 'France', label: 'France' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambie', label: 'Gambie' },
  { value: 'Géorgie', label: 'Géorgie' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Grèce', label: 'Grèce' },
  { value: 'Grenade', label: 'Grenade' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guinée', label: 'Guinée' },
  { value: 'Guinée équatoriale', label: 'Guinée équatoriale' },
  { value: 'Guinée-Bissau', label: 'Guinée-Bissau' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'HT', label: 'Haïti' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HU', label: 'Hongrie' },
  { value: 'IN', label: 'Inde' },
  { value: 'Indonésie', label: 'Indonésie' },
  { value: 'Irak', label: 'Irak' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Irlande', label: 'Irlande' },
  { value: 'Islande', label: 'Islande' },
  { value: 'Israël', label: 'Israël' },
  { value: 'Italie', label: 'Italie' },
  { value: 'Jamaïque', label: 'Jamaïque' },
  { value: 'Japon', label: 'Japon' },
  { value: 'Jordanie', label: 'Jordanie' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kirghizistan', label: 'Kirghizistan' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: 'Koweït', label: 'Koweït' },
  { value: 'Laos', label: 'Laos' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Lettonie', label: 'Lettonie' },
  { value: 'Liban', label: 'Liban' },
  { value: 'Libéria', label: 'Libéria' },
  { value: 'Libye', label: 'Libye' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lituanie', label: 'Lituanie' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Macédoine du Nord', label: 'Macédoine du Nord' },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malaisie', label: 'Malaisie' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malte', label: 'Malte' },
  { value: 'Maroc', label: 'Maroc' },
  { value: 'Îles Marshall', label: 'Îles Marshall' },
  { value: 'Maurice', label: 'Maurice' },
  { value: 'Mauritanie', label: 'Mauritanie' },
  { value: 'Mexique', label: 'Mexique' },
  { value: 'Micronésie', label: 'Micronésie' },
  { value: 'Moldavie', label: 'Moldavie' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolie', label: 'Mongolie' },
  { value: 'Monténégro', label: 'Monténégro' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Namibie', label: 'Namibie' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Népal', label: 'Népal' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'Norvège', label: 'Norvège' },
  { value: 'Nouvelle-Zélande', label: 'Nouvelle-Zélande' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Ouganda', label: 'Ouganda' },
  { value: 'Ouzbékistan', label: 'Ouzbékistan' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palaos', label: 'Palaos' },
  { value: 'Palestine', label: 'Palestine' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papouasie-Nouvelle-Guinée', label: 'Papouasie-Nouvelle-Guinée' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Pays-Bas', label: 'Pays-Bas' },
  { value: 'Pérou', label: 'Pérou' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Pologne', label: 'Pologne' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Roumanie', label: 'Roumanie' },
  { value: 'Royaume-Uni', label: 'Royaume-Uni' },
  { value: 'Russie', label: 'Russie' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Saint-Kitts-et-Nevis', label: 'Saint-Kitts-et-Nevis' },
  { value: 'Saint-Marin', label: 'Saint-Marin' },
  { value: 'Saint-Vincent-et-les-Grenadines', label: 'Saint-Vincent-et-les-Grenadines' },
  { value: 'Sainte-Lucie', label: 'Sainte-Lucie' },
  { value: 'Îles Salomon', label: 'Îles Salomon' },
  { value: 'Salvador', label: 'Salvador' },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'Sao Tomé-et-Principe', label: 'Sao Tomé-et-Principe' },
  { value: 'Sénégal', label: 'Sénégal' },
  { value: 'Serbie', label: 'Serbie' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapour', label: 'Singapour' },
  { value: 'Slovaquie', label: 'Slovaquie' },
  { value: 'Slovénie', label: 'Slovénie' },
  { value: 'Somalie', label: 'Somalie' },
  { value: 'Soudan', label: 'Soudan' },
  { value: 'Soudan du Sud', label: 'Soudan du Sud' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Suède', label: 'Suède' },
  { value: 'Suisse', label: 'Suisse' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Eswatini', label: 'Eswatini' },
  { value: 'Syrie', label: 'Syrie' },
  { value: 'Tadjikistan', label: 'Tadjikistan' },
  { value: 'Tanzanie', label: 'Tanzanie' },
  { value: 'Tchad', label: 'Tchad' },
  { value: 'République tchèque', label: 'République tchèque' },
  { value: 'Thaïlande', label: 'Thaïlande' },
  { value: 'Timor oriental', label: 'Timor oriental' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Trinité-et-Tobago', label: 'Trinité-et-Tobago' },
  { value: 'Tunisie', label: 'Tunisie' },
  { value: 'Turkménistan', label: 'Turkménistan' },
  { value: 'Turquie', label: 'Turquie' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Vatican', label: 'Vatican' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Viêt Nam', label: 'Viêt Nam' },
  { value: 'Yémen', label: 'Yémen' },
  { value: 'Zambie', label: 'Zambie' },
  { value: 'Zimbabwe', label: 'Zimbabwe' }
];

